-- USER table
CREATE TABLE USER (
    userid      INT PRIMARY KEY,
    role        VARCHAR(50),
    name        VARCHAR(100),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    password    VARCHAR(255),
    status      VARCHAR(50)
);

-- MESSAGE table (exchange relationship between users)
CREATE TABLE MESSAGE (
    messageid   INT PRIMARY KEY,
    senderid    INT NOT NULL,
    receiverid  INT NOT NULL,
    content     TEXT,
    timestamp   DATETIME,
    read        BOOLEAN,
    FOREIGN KEY (senderid)   REFERENCES USER(userid),
    FOREIGN KEY (receiverid) REFERENCES USER(userid)
);

-- NOTIFICATION table (receives relationship: user receives N notifications)
CREATE TABLE NOTIFICATION (
    notificationid  INT PRIMARY KEY,
    userid          INT NOT NULL,
    type            VARCHAR(50),
    title           VARCHAR(150),
    body            TEXT,
    read            BOOLEAN,
    FOREIGN KEY (userid) REFERENCES USER(userid)
);

-- PROJECT table (owned by a client user, managed by a manager user)
CREATE TABLE PROJECT (
    projectid   INT PRIMARY KEY,
    clientid    INT NOT NULL,
    managerid   INT NOT NULL,
    name        VARCHAR(150),
    location    VARCHAR(255),
    budget      DECIMAL(15, 2),
    spent       DECIMAL(15, 2),
    progress    DECIMAL(5, 2),
    status      VARCHAR(50),
    startdate   DATE,
    enddate     DATE,
    FOREIGN KEY (clientid)  REFERENCES USER(userid),
    FOREIGN KEY (managerid) REFERENCES USER(userid)
);

-- TASK table (contained in a project, assigned to a user)
CREATE TABLE TASK (
    taskid      INT PRIMARY KEY,
    projectid   INT NOT NULL,
    assignedto  INT,
    title       VARCHAR(150),
    priority    VARCHAR(50),
    status      VARCHAR(50),
    startdate   DATE,
    deadline    DATE,
    progress    DECIMAL(5, 2),
    FOREIGN KEY (projectid)  REFERENCES PROJECT(projectid),
    FOREIGN KEY (assignedto) REFERENCES USER(userid)
);

-- REPORT table (submitted by a user, tracked by a project)
CREATE TABLE REPORT (
    reportid    INT PRIMARY KEY,
    projectid   INT NOT NULL,
    submittedby INT NOT NULL,
    title       VARCHAR(150),
    date        DATE,
    progress    DECIMAL(5, 2),
    status      VARCHAR(50),
    workdone    TEXT,
    FOREIGN KEY (projectid)   REFERENCES PROJECT(projectid),
    FOREIGN KEY (submittedby) REFERENCES USER(userid)
);

-- EXPENSE table (recorded by a user, belongs to a project)
CREATE TABLE EXPENSE (
    expenseid   INT PRIMARY KEY,
    projectid   INT NOT NULL,
    recordedby  INT NOT NULL,
    category    VARCHAR(100),
    amount      DECIMAL(15, 2),
    date        DATE,
    FOREIGN KEY (projectid)  REFERENCES PROJECT(projectid),
    FOREIGN KEY (recordedby) REFERENCES USER(userid)
);

-- BILL table (generated by a project, incurred/linked to expenses)
CREATE TABLE BILL (
    billid          INT PRIMARY KEY,
    projectid       INT NOT NULL,
    generatedby     INT NOT NULL,
    amount          DECIMAL(15, 2),
    milestone       VARCHAR(150),
    status          VARCHAR(50),
    duedate         DATE,
    decisiondate    DATE,
    FOREIGN KEY (projectid)   REFERENCES PROJECT(projectid),
    FOREIGN KEY (generatedby) REFERENCES USER(userid)
);

-- EXPENSE_BILL junction table (logs relationship: expense logs into bill)
CREATE TABLE EXPENSE_BILL (
    expenseid   INT NOT NULL,
    billid      INT NOT NULL,
    PRIMARY KEY (expenseid, billid),
    FOREIGN KEY (expenseid) REFERENCES EXPENSE(expenseid),
    FOREIGN KEY (billid)    REFERENCES BILL(billid)
);
